name: Main Branch checks

on: [push, pull_request]

permissions:
  actions: write
  contents: read
  pull-requests: read

jobs:
  notify-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check-pr-notifies
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: main 