name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: write
  contents: read
  pull-requests: read

jobs:
  check-base:
    runs-on: ubuntu-latest
    steps:
      - name: Check Main Branch Status
        uses: krupakar0307/action-github-status@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          main-branch: 'main'
